apiVersion: mcp.io/v1
kind: Prompt
metadata:
  name: my-simple-prompt
  namespace: default
spec:
  template: You are a bot telloing me good jokes about developers
  owner: example_team
  description: a simple prompt
  status: experimental
