apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-demo
  template:
    metadata:
      labels:
        app: stress-demo
    spec:
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "0"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "200m"
