apiVersion: mcp.io/v1
kind: Prompt
metadata:
  name: code-review-prompt
  namespace: default
spec:
  description: "A prompt template for conducting code reviews with AI assistance"
  status: stable
  owner: platform_team
  template: |
    # Code Review Prompt
    
    Please review the following code changes:
    
    **File**: {{file_path}}
    **Changes**: {{changes}}
    
    Focus on:
    - Code quality and best practices
    - Security considerations
    - Performance implications
    - Maintainability
    
    Provide specific feedback and suggestions for improvement.
  arguments:
    - name: file_path
      description: The path to the file being reviewed
      required: true
    - name: changes
      description: The code changes to be reviewed
      required: true
    - name: focus_areas
      description: Specific areas to focus the review on
      required: false